version: '2'
services:
    agent:
        image: zeye/agent
        container_name: zeye-agent
        command: python /agent.py run -d \
            --device=/dev/ttyAMA0 \
            --config=/python-openzwave/openzwave/config \
            --user_path=/data
        volumes:
            - ./data:/data
            - ./agent.py:/agent.py
        devices:
            - "/dev/ttyAMA0:/dev/ttyAMA0"
        stop_signal: SIGINT
        privileged: true
