version: '2'
services:
    agent:
        image: zeye/agent
        container_name: zeye-agent
        command: python agent.py -d run
        volumes:
            - ./agent.py:/agent.py:ro
        stop_signal: SIGINT
        expose:
            - '162/udp'
