version: '2'
services:
    agent:
        image: zeye/agent-rpi
        container_name: zeye-agent
        command: python /agent.py -d run --device=/dev/ttyAMA0 --config=/usr/share/openzwave/config --user_path=/data
        volumes:
            - ./data:/data
            - ./agent.py:/agent.py
        devices:
            - "/dev/ttyAMA0:/dev/ttyAMA0"
        stop_signal: SIGINT
        privileged: true
