version: '2'
services:
    agent:
        image: alidron/rpi-python-openzwave:master
        container_name: zeye-agent
        command: python /agent.py run -d \
            --device=/dev/ttyAMA0 \
            --config=/usr/share/openzwave \
            --user_path=/data
        volumes:
            - ./data:/data
            - ./agent.py:/agent.py
        devices:
            - "/dev/ttyAMA0:/dev/ttyAMA0"
        stop_signal: SIGINT
        privileged: true
